# Generated by Django 2.1.2 on 2018-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEPE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='penulis',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
